enum AppAccessibilityID {
    static let debugOpenGallery = "app.debug.open-component-gallery"
    static let debugOpenInteractionLab = "app.debug.open-interaction-lab"
    static let followedForumsRoot = "app.root.followed-forums"
    static let galleryAppearance = "design-system.gallery.appearance"
    static let galleryDynamicType = "design-system.gallery.dynamic-type"
    static let galleryReduceMotion = "design-system.gallery.reduce-motion"
    static let galleryRoot = "design-system.gallery"
    static let layoutCompact = "app.shell.layout.compact"
    static let layoutRegular = "app.shell.layout.regular"
    static let openForum = "app.fixture.root.open-forum"
    static let openSubposts = "app.fixture.thread.open-subposts"
    static let openThread = "app.fixture.forum.open-thread"
    static let recommendationsRoot = "app.root.recommendations"
    static let routeForum = "app.route.forum"
    static let routeSubposts = "app.route.subposts"
    static let routeThread = "app.route.thread"
    static let settingsRoot = "app.root.settings"
    static let shellRoot = "app.shell.root"
    static let shellScenario = "app.shell.scenario"
    static let shellTitle = "app.shell.title"
    static let tabFollowedForums = "app.tab.followed-forums"
    static let tabRecommendations = "app.tab.recommendations"
    static let tabSettings = "app.tab.settings"
}
